spring:
  application:
    name: daedongmap

  datasource:
    #        H2
#    url: jdbc:h2:mem:daedongmap-db
#    username: sa
#  h2:
#    console:
#      enabled: true

  #        MySQL
    url: jdbc:mysql://daedongmap-db:3306/daedongmap
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1234

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
  
#  설정 파일 생성 시 까먹지 말고 include 하기
  profiles:
    include: aws, oauth, secret
